### ISSUE TITLE
Is there a specific configuration in OneDrive that must be used??

### ISSUE THREAD

**Issue by alejandropts1** [SafeBreach-Labs/DoubleDrive#6]
Hi,

When i try to execute the tool endpoint_takeover.exe (also tried with the script itself) i always receive the following error.

Extracting Windows Live ID token from OneDrive's logs
ObfuscationStringMap.txt not found in C:\Users\vmtest\AppData\Local\Microsoft\OneDrive\logs\Personal.
Recovered Unobfuscation key <redacted>=  , version=1, utf_type=utf16
Traceback (most recent call last):
  File "endpoint_takeover.py", line 45, in <module>
  File "endpoint_takeover.py", line 28, in main
  File "doubledrive\endpoint_takeover_utils\token_extraction\onedrive\onedrive_token_extraction.py", line 134, in steal_onedrive_wlid_token
  File "doubledrive\endpoint_takeover_utils\token_extraction\onedrive\onedrive_token_extraction.py", line 118, in extract_windows_live_id_from_odls
  File "doubledrive\endpoint_takeover_utils\token_extraction\onedrive\odl_parser\odl.py", line 359, in get_odl_rows
  File "doubledrive\endpoint_takeover_utils\token_extraction\onedrive\odl_parser\odl.py", line 285, in process_odl
  File "construct\core.py", line 288, in parse
  File "construct\core.py", line 300, in parse_stream
  File "construct\core.py", line 312, in _parsereport
  File "construct\core.py", line 2120, in _parse
  File "construct\core.py", line 312, in _parsereport
  File "construct\core.py", line 2653, in _parse
  File "construct\core.py", line 312, in _parsereport
  File "construct\core.py", line 1041, in _parse
  File "construct\core.py", line 91, in stream_read
construct.core.StreamError: Error in path (parsing) -> data_len
stream read less than specified amount, expected 4, found 3
[6468] Failed to execute script 'endpoint_takeover' due to unhandled exception!

Do you know if there are issues on testing this technique when using personal accounts instead of corporative accounts??

**Comment by oryair1** [comment]
Hi :)
I developed DoubleDrive to work with personal accounts actually. Adjustments are required in order for it to work with business accounts too. It seems like the exception you get is happening while OneDrive's logs are parsed in order to look for the WLID token in them. An important thing to mention is that the issue of the token being written into the logs is patched by now. I implemented an alternative way to get it by extracting it from a process dump of OneDrive. I didn't write the script that parses the logs. I took it from this repo and modified it a bit for my purposes - https://github.com/ydkhatri/OneDrive

It looks like there is something wrong with one of your logs. I never saw this situation before. It is also possible that Microsoft changed the format of the logs in a newer OneDrive version. 

What I advise to do is to:
• Empty the ODL folder from logs and then try to run the tool again. Go to %localappdata%\Microsoft\OneDrive\logs\Personal and delete all .odl, .odlgz, .odlsent, .aodl files.
• If that doesn't help, and you don't care specifically about the stage of trying to extract the token from the logs, you can also skip that stage by patching the steal_onedrive_wlid_token() function to use only the extract_windows_live_id_from_procdump() function instead of first trying to use extract_windows_live_id_from_odls()

**Comment by alejandropts1** [comment]
Thank you so much for such a detailed answer, i'll test your alternatives and maybe submit a PR to the documentation if you want.
